### PR TITLE
fix #obj returns 0 if obj:__len() does not return a number #342

### LINKED ISSUE #342: `#obj` only return integers
- [x] GopherLua is a Lua5.1 implementation. You should be familiar with Lua programming language. Have you read [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) carefully?
- [x] GopherLua is a Lua5.1 implementation.  In Lua, to keep it simple, **it is more important to remove functionalities rather than to add functionalities unlike other languages** . If you are going to introduce some new cool functionalities into the GopherLua code base and the functionalities can be implemented by existing APIs, It should be implemented as a library. 

Please answer the following before submitting your issue:

1. What version of GopherLua are you using? : 

`github.com/yuin/gopher-lua v0.0.0-20210529063254-f4c35e4016d9`

2. What version of Go are you using? : 

`1.16`

3. What operating system and processor architecture are you using? :

`NixOS AMD64`

4. What did you do? :

Tried to define a __len function to use the # operator while trying to implement a port of the lpeg parser for gopher-lua but the tests didn't pass because it returns 0 instead of a new pattern object, __len is defined correctly and works if I run `obj:__len()` instead of `#obj`

5. What did you expect to see? :

`#obj` returning a new object in that case, or the value returned by `obj.__len(obj)`

6. What did you see instead? :

`0`

Relevant links:

http://www.inf.puc-rio.br/~roberto/lpeg/#op-len
https://github.com/lucasew/doc_project/blob/eb62e6b5c9bcf849c25d1aa9f255e3cccc1e23dc/lua/stdlib/parser/test.lua#L68
https://github.com/lucasew/doc_project/blob/eb62e6b5c9bcf849c25d1aa9f255e3cccc1e23dc/lua/stdlib/parser/pattern.go#L42

Example:
```lua
mt = {
    __index = mt,
    __len = function (self)
        return {hello = "world"}
    end
}

v = {}
v.__index = v

setmetatable(v, mt)

print(#v)
```

```
> mt = {
>>     __index = mt,
>>     __len = function (self)
>>         return {hello = "world"}
>>     end
>> }
> 
> v = {}
> v.__index = v
> 
> setmetatable(v, mt)
> 
> print(#v)
0
>  
```
PUC Lua returns a table reference instead

### PR DESCRIPTION
**Pull request by lucasew**
Signed-off-by: lucasew <lucas59356@gmail.com>

Fixes #342 

Changes proposed in this pull request:

- a
- b
- c
- d

### CODE REVIEW

File: table_test.go [hunk 1]
```diff
@@ -27,6 +27,30 @@ func TestTableLen(t *testing.T) {
 	errorIfNotEqual(t, 3, tbl.Len())
 }
 
+func TestTableLenType(t *testing.T) {
```
Comment (0x501D) [inline table_test.go:30]: This test fails on LuaJIT 2.0.5  and Lua 5.1.5.
It this OK?

File: vm.go [hunk 2]
```diff
@@ -549,7 +549,7 @@ func init() {
 					if ret.Type() == LTNumber {
 						reg.SetNumber(RA, ret.(LNumber))
 					} else {
-						reg.SetNumber(RA, LNumber(0))
+						reg.Set(RA, ret)
```
Comment (0x501D) [inline vm.go:552]: vim-go: Do not edit this file! /home/void/tmp/1111/gopher-lua/vm.go is a generated file.

File: table_test.go [hunk 3]
```diff
@@ -27,6 +27,30 @@ func TestTableLen(t *testing.T) {
...
+    L := NewState(Options{})
```
Comment (0x501D) [inline table_test.go:31]: go fmt
